# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'quavi' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for quavi
	pod 'MapboxNavigation', '~> 0.38.2'
	pod 'Firebase/Auth'
	pod 'Firebase/Firestore'
	pod 'Firebase/Storage'

  #Pod for Image  caching 
        pod 'Kingfisher', '~> 5.0'

  target 'quaviTests' do
    inherit! :search_paths
    # Pods for testing
	pod 'Quick'
	pod 'Nimble'
  end

end
